spring.application.name=sigaplus
server.port=3000
spring.sql.init.mode=always
jwt.public.key=classpath:keypub.pem
jwt.private.key=classpath:newkey.pri.pem
jwt.secret=MEUSuperSegredoAltamenteSecretoDeCriptografiaParaJWTQueSoMeuBackendSabe
jwt.expiration-ms=3600000
spring.datasource.url=jdbc:mysql://localhost:3306/sigaplus?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=@Maninhox077
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.show-sql=true
debug=true

spring.security.oauth2.client.registration.google.client-id=285980298029-o88dfr1jmk96f9iq918f3hrrisheasr6.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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